version: '3.7'
services:
   database:
     image: mysql:latest
     environment:
       MYSQL_ROOT_PASSWORD: 'admin'
     ports:
       - '3306:3306'
   user-management:
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    links:
      - database
