spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wastermant?createDatabaseIfNotExist=true
    username: root
    password: admin
    testWhileIdle: true
    validationQuery: SELECT 1